// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{0}
}
func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (dst *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(dst, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type MoveAction struct {
	Pos                  *Vector  `protobuf:"bytes,1,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveAction) Reset()         { *m = MoveAction{} }
func (m *MoveAction) String() string { return proto.CompactTextString(m) }
func (*MoveAction) ProtoMessage()    {}
func (*MoveAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{1}
}
func (m *MoveAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveAction.Unmarshal(m, b)
}
func (m *MoveAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveAction.Marshal(b, m, deterministic)
}
func (dst *MoveAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveAction.Merge(dst, src)
}
func (m *MoveAction) XXX_Size() int {
	return xxx_messageInfo_MoveAction.Size(m)
}
func (m *MoveAction) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveAction.DiscardUnknown(m)
}

var xxx_messageInfo_MoveAction proto.InternalMessageInfo

func (m *MoveAction) GetPos() *Vector {
	if m != nil {
		return m.Pos
	}
	return nil
}

type Action struct {
	Credentials *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*Action_Move
	Type                 isAction_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{2}
}
func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (dst *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(dst, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type isAction_Type interface {
	isAction_Type()
}

type Action_Move struct {
	Move *MoveAction `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

func (*Action_Move) isAction_Type() {}

func (m *Action) GetType() isAction_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Action) GetMove() *MoveAction {
	if x, ok := m.GetType().(*Action_Move); ok {
		return x.Move
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Action) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Action_OneofMarshaler, _Action_OneofUnmarshaler, _Action_OneofSizer, []interface{}{
		(*Action_Move)(nil),
	}
}

func _Action_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Action)
	// type
	switch x := m.Type.(type) {
	case *Action_Move:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Move); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Action.Type has unexpected type %T", x)
	}
	return nil
}

func _Action_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Action)
	switch tag {
	case 2: // type.move
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveAction)
		err := b.DecodeMessage(msg)
		m.Type = &Action_Move{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Action_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Action)
	// type
	switch x := m.Type.(type) {
	case *Action_Move:
		s := proto.Size(x.Move)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type State struct {
	JsonState            []byte   `protobuf:"bytes,1,opt,name=json_state,json=jsonState,proto3" json:"json_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{3}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (dst *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(dst, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetJsonState() []byte {
	if m != nil {
		return m.JsonState
	}
	return nil
}

type Credentials struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{4}
}
func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (dst *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(dst, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_350702c7b791357b, []int{5}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Vector)(nil), "server.Vector")
	proto.RegisterType((*MoveAction)(nil), "server.MoveAction")
	proto.RegisterType((*Action)(nil), "server.Action")
	proto.RegisterType((*State)(nil), "server.State")
	proto.RegisterType((*Credentials)(nil), "server.Credentials")
	proto.RegisterType((*Empty)(nil), "server.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpacyServerClient is the client API for SpacyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpacyServerClient interface {
	GetCredentials(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Credentials, error)
	GetUpdates(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (SpacyServer_GetUpdatesClient, error)
	Act(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Empty, error)
}

type spacyServerClient struct {
	cc *grpc.ClientConn
}

func NewSpacyServerClient(cc *grpc.ClientConn) SpacyServerClient {
	return &spacyServerClient{cc}
}

func (c *spacyServerClient) GetCredentials(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Credentials, error) {
	out := new(Credentials)
	err := c.cc.Invoke(ctx, "/server.SpacyServer/GetCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spacyServerClient) GetUpdates(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (SpacyServer_GetUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SpacyServer_serviceDesc.Streams[0], "/server.SpacyServer/GetUpdates", opts...)
	if err != nil {
		return nil, err
	}
	x := &spacyServerGetUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SpacyServer_GetUpdatesClient interface {
	Recv() (*State, error)
	grpc.ClientStream
}

type spacyServerGetUpdatesClient struct {
	grpc.ClientStream
}

func (x *spacyServerGetUpdatesClient) Recv() (*State, error) {
	m := new(State)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *spacyServerClient) Act(ctx context.Context, in *Action, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/server.SpacyServer/Act", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpacyServerServer is the server API for SpacyServer service.
type SpacyServerServer interface {
	GetCredentials(context.Context, *Empty) (*Credentials, error)
	GetUpdates(*Credentials, SpacyServer_GetUpdatesServer) error
	Act(context.Context, *Action) (*Empty, error)
}

func RegisterSpacyServerServer(s *grpc.Server, srv SpacyServerServer) {
	s.RegisterService(&_SpacyServer_serviceDesc, srv)
}

func _SpacyServer_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacyServerServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.SpacyServer/GetCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacyServerServer).GetCredentials(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpacyServer_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Credentials)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpacyServerServer).GetUpdates(m, &spacyServerGetUpdatesServer{stream})
}

type SpacyServer_GetUpdatesServer interface {
	Send(*State) error
	grpc.ServerStream
}

type spacyServerGetUpdatesServer struct {
	grpc.ServerStream
}

func (x *spacyServerGetUpdatesServer) Send(m *State) error {
	return x.ServerStream.SendMsg(m)
}

func _SpacyServer_Act_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Action)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpacyServerServer).Act(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.SpacyServer/Act",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpacyServerServer).Act(ctx, req.(*Action))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpacyServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.SpacyServer",
	HandlerType: (*SpacyServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentials",
			Handler:    _SpacyServer_GetCredentials_Handler,
		},
		{
			MethodName: "Act",
			Handler:    _SpacyServer_Act_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUpdates",
			Handler:       _SpacyServer_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_350702c7b791357b) }

var fileDescriptor_protocol_350702c7b791357b = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdd, 0xfe, 0x89, 0x74, 0x52, 0x73, 0x18, 0x2f, 0xa5, 0x50, 0x28, 0x4b, 0x91, 0x9e,
	0x82, 0x44, 0x7d, 0x80, 0x2a, 0x52, 0x2f, 0x5e, 0x36, 0xe8, 0x55, 0xe2, 0x66, 0x0e, 0x91, 0x36,
	0xbb, 0x26, 0x43, 0x68, 0x1e, 0xc6, 0x77, 0x95, 0x6c, 0x4c, 0x1b, 0xa1, 0xb7, 0x9d, 0x9d, 0xdf,
	0x37, 0xdf, 0x37, 0xbb, 0x10, 0xd8, 0xc2, 0xb0, 0xd1, 0x66, 0x17, 0xba, 0x03, 0x7a, 0x25, 0x15,
	0x15, 0x15, 0x72, 0x05, 0xde, 0x3b, 0x69, 0x36, 0x05, 0x4e, 0x41, 0x1c, 0x66, 0x62, 0x29, 0xd6,
	0x42, 0x89, 0x43, 0x53, 0xd5, 0xb3, 0x41, 0x5b, 0xd5, 0x32, 0x04, 0x78, 0x35, 0x15, 0x6d, 0x34,
	0x67, 0x26, 0xc7, 0x25, 0x0c, 0xad, 0x29, 0x1d, 0xeb, 0x47, 0x41, 0xd8, 0x4e, 0x0a, 0xdb, 0x31,
	0xaa, 0x69, 0xc9, 0x6f, 0xf0, 0xfe, 0xd8, 0x07, 0xf0, 0x75, 0x41, 0x29, 0xe5, 0x9c, 0x25, 0xbb,
	0x4e, 0x73, 0xdd, 0x69, 0x9e, 0x4e, 0x2d, 0xd5, 0xe7, 0x70, 0x0d, 0xa3, 0xbd, 0xa9, 0xc8, 0x25,
	0xf0, 0x23, 0xec, 0xf8, 0x53, 0x88, 0x97, 0x0b, 0xe5, 0x88, 0x47, 0x0f, 0x46, 0x5c, 0x5b, 0x92,
	0x37, 0x30, 0x8e, 0x39, 0x61, 0xc2, 0x05, 0xc0, 0x57, 0x69, 0xf2, 0x8f, 0xb2, 0xa9, 0x9c, 0xe1,
	0x54, 0x4d, 0x9a, 0x1b, 0xd7, 0x96, 0x0b, 0xf0, 0x7b, 0xae, 0x18, 0xc0, 0x20, 0x4b, 0x1d, 0x35,
	0x51, 0x83, 0x2c, 0x95, 0x97, 0x30, 0x7e, 0xde, 0x5b, 0xae, 0xa3, 0x1f, 0x01, 0x7e, 0x6c, 0x13,
	0x5d, 0xc7, 0xce, 0x1a, 0xef, 0x21, 0xd8, 0x12, 0xf7, 0xa5, 0x57, 0x5d, 0x2a, 0x27, 0x98, 0x9f,
	0x5b, 0x0a, 0x23, 0x80, 0x2d, 0xf1, 0x9b, 0x4d, 0x13, 0xa6, 0x12, 0xcf, 0x21, 0xf3, 0xe3, 0x18,
	0x97, 0xef, 0x56, 0xe0, 0x0a, 0x86, 0x1b, 0xcd, 0x78, 0x7c, 0xd8, 0x76, 0xe1, 0xf9, 0x7f, 0xbb,
	0x4f, 0xcf, 0xfd, 0xe3, 0xdd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x9f, 0xf7, 0x21, 0xd9,
	0x01, 0x00, 0x00,
}
